# Generated by Django 2.1.2 on 2018-11-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackpart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='lastname',
            new_name='email',
        ),
    ]
