# Generated by Django 2.1.2 on 2018-11-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackpart', '0002_auto_20181103_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='fullname',
            new_name='name',
        ),
    ]
